services:
  mongo:
    image: mongo:7
    container_name: fiberpass-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - fiberpass-mongo:/data/db

volumes:
  fiberpass-mongo:
